mod address_operands;
pub mod call_frame;
mod eravm_error;
pub mod heaps;
mod op_handlers;
mod opcode;
pub mod output;
mod ptr_operator;
pub mod state;
pub mod store;
pub mod tracers;
pub mod utils;
pub mod value;
pub mod vm;
use op_handlers::event::event;
use op_handlers::panic::panic;
pub use opcode::Opcode;
pub use state::VMState;
pub use vm::LambdaVm;
use zkevm_opcode_defs::Opcode as Variant;
