name: CI

on:
  merge_group:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  RUST_VERSION: 1.78.0
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Rustup toolchain install
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_VERSION }}

      - name: Run cargo check
        run: cargo check --workspace --all-features --all-targets

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_VERSION }}
          components: rustfmt, clippy

      - name: Run cargo fmt
        run: cargo fmt --all -- --check

      - name: Run clippy
        run: cargo clippy --workspace --all-features --benches --examples --tests -- -D warnings

  test-with-compiler-tester:
    strategy:
      fail-fast: false
      matrix:
        testgroup: [
          tests/solidity/simple/*.sol, # PASSING
          #tests/solidity/simple/algorithm, # FAILING
          #tests/solidity/simple/array, # FAILING
          tests/solidity/simple/block, # PASSING
          #tests/solidity/simple/call_chain, # FAILING
          #tests/solidity/simple/conditional, # FAILING
          tests/solidity/simple/constant_expressions, # PASSING
          tests/solidity/simple/constants, # PASSING
          tests/solidity/simple/constructor, # PASSING
          tests/solidity/simple/context, # PASSING
          tests/solidity/simple/destructuring, # PASSING
          #tests/solidity/simple/error, # FAILING
          tests/solidity/simple/events,
          #tests/solidity/simple/expression, # FAILING
          tests/solidity/simple/fallback, # PASSING
          #tests/solidity/simple/fat_ptr, # FAILING
          #tests/solidity/simple/function, # FAILING
          #tests/solidity/simple/gas_value, # FAILING
          #tests/solidity/simple/immutable, # FAILING
          tests/solidity/simple/interface,
          #tests/solidity/simple/internal_function_pointers, # FAILING
          tests/solidity/simple/linearity, # PASSING
          tests/solidity/simple/loop,
          tests/solidity/simple/match, # PASSING
          #tests/solidity/simple/modular, # FAILING
          #tests/solidity/simple/operator, # FAILING
          tests/solidity/simple/order, # PASSING
          #tests/solidity/simple/overflow, # FAILING
          tests/solidity/simple/pointer, # PASSING
          tests/solidity/simple/recursion, # PASSING
          tests/solidity/simple/return, # PASSING
          #tests/solidity/simple/solidity_by_example, # FAILING
          tests/solidity/simple/storage,
          tests/solidity/simple/structure, # PASSING
          tests/solidity/simple/system, # PASSING
          #tests/solidity/simple/try_catch, # FAILING
          tests/solidity/simple/unused, # PASSING
          tests/solidity/simple/yul_instructions,
          #tests/solidity/simple/yul_semantic, # FAILING
          tests/vyper/complex/create_minimal_proxy_to,
          tests/vyper/complex/many_arguments,
          tests/vyper/complex/invalid_signature,
          tests/vyper/complex/voting,
          tests/vyper/complex/nested_calls,
          tests/vyper/complex/value,
          tests/vyper/complex/default,
          tests/vyper/complex/storage,
          tests/vyper/complex/interface_casting,
          tests/vyper/complex/call_chain,
          tests/vyper/complex/array_one_element,
          tests/vyper/complex/solidity_by_example,
          tests/vyper/complex/sum_of_squares,
          tests/vyper/complex/create_from_blueprint,
          tests/vyper/complex/indirect_recursion_fact,
          tests/vyper/complex/defi,
          tests/vyper/complex/call_by_signature,
          tests/vyper/complex/ethereum,
          tests/vyper/simple/*.vy,
          tests/vyper/simple/order,
          tests/vyper/simple/interface,
          tests/vyper/simple/immutable,
          tests/vyper/simple/conditional,
          tests/vyper/simple/unchecked_math,
          tests/vyper/simple/fallback,
          tests/vyper/simple/array,
          tests/vyper/simple/destructuring,
          tests/vyper/simple/revert_on_failure,
          tests/vyper/simple/unused,
          tests/vyper/simple/return,
          tests/vyper/simple/function,
          tests/vyper/simple/algorithm,
          tests/vyper/simple/storage,
          tests/vyper/simple/overflow,
          tests/vyper/simple/modular,
          tests/vyper/simple/solidity_by_example,
          tests/vyper/simple/expression,
          tests/vyper/simple/events,
          tests/vyper/simple/structure,
          tests/vyper/simple/error,
          tests/vyper/simple/operator,
          tests/vyper/simple/loop,
          tests/vyper/simple/constructor,
          tests/vyper/simple/built_in_functions,
          tests/vyper/simple/block,
          tests/vyper/ethereum/*.vy,
          tests/vyper/ethereum/smoke,
          tests/vyper/ethereum/strings,
          tests/vyper/ethereum/immutable,
          tests/vyper/ethereum/types,
          tests/vyper/ethereum/ecrecover,
          tests/vyper/ethereum/operators,
          tests/vyper/ethereum/optimizer,
          tests/vyper/ethereum/fallback,
          tests/vyper/ethereum/conversions,
          tests/vyper/ethereum/array,
          tests/vyper/ethereum/calldata,
          tests/vyper/ethereum/abiencodedecode,
          tests/vyper/ethereum/accessor,
          tests/vyper/ethereum/constants,
          tests/vyper/ethereum/builtinFunctions,
          tests/vyper/ethereum/constantEvaluator,
          tests/vyper/ethereum/abiEncoderV2,
          tests/vyper/ethereum/underscore,
          tests/vyper/ethereum/state,
          tests/vyper/ethereum/storage,
          tests/vyper/ethereum/interfaceID,
          tests/vyper/ethereum/various,
          tests/vyper/ethereum/isoltestTesting,
          tests/vyper/ethereum/specialFunctions,
          tests/vyper/ethereum/functionCall,
          tests/vyper/ethereum/cleanup,
          tests/vyper/ethereum/reverts,
          tests/vyper/ethereum/structs,
          tests/vyper/ethereum/memoryManagement,
          tests/vyper/ethereum/variables,
          tests/vyper/ethereum/arithmetics,
          tests/vyper/ethereum/getters,
          tests/vyper/ethereum/expressions,
          tests/vyper/ethereum/revertStrings,
          tests/vyper/ethereum/integer,
          tests/vyper/ethereum/literals,
          tests/vyper/ethereum/viaYul,
          tests/vyper/ethereum/events,
          tests/vyper/ethereum/abiEncoderV1,
          tests/vyper/ethereum/constructor,
          tests/llvm/memset,
          tests/llvm/signed-operations,
          tests/llvm/load,
          tests/llvm/intrinsics,
          tests/llvm/stack,
          tests/llvm/store,
          tests/solidity/complex/interpreter,
          tests/solidity/complex/default_single_file,
          tests/solidity/complex/import_library_inline,
          tests/solidity/complex/many_arguments,
          tests/solidity/complex/invalid_signature,
          tests/solidity/complex/forwarding,
          tests/solidity/complex/library_call_tuple,
          tests/solidity/complex/voting,
          tests/solidity/complex/nested_calls,
          tests/solidity/complex/value,
          tests/solidity/complex/default,
          tests/solidity/complex/parser,
          tests/solidity/complex/storage,
          tests/solidity/complex/immutable_delegate_call,
          tests/solidity/complex/interface_casting,
          tests/solidity/complex/yul_instructions,
          tests/solidity/complex/call_chain,
          tests/solidity/complex/internal_function_pointers,
          tests/solidity/complex/array_one_element,
          tests/solidity/complex/evaluation_order,
          tests/solidity/complex/solidity_by_example,
          tests/solidity/complex/sum_of_squares,
          tests/solidity/complex/indirect_recursion_fact,
          tests/solidity/complex/try_catch,
          tests/solidity/complex/create,
          tests/solidity/complex/defi,
          tests/solidity/complex/call_by_signature,
          tests/solidity/ethereum/smoke,
          tests/solidity/ethereum/experimental,
          tests/solidity/ethereum/uninitializedFunctionPointer,
          tests/solidity/ethereum/shanghai,
          tests/solidity/ethereum/strings,
          tests/solidity/ethereum/immutable,
          tests/solidity/ethereum/modifiers,
          tests/solidity/ethereum/types,
          tests/solidity/ethereum/inlineAssembly,
          tests/solidity/ethereum/metaTypes,
          tests/solidity/ethereum/externalContracts,
          tests/solidity/ethereum/ecrecover,
          tests/solidity/ethereum/operators,
          tests/solidity/ethereum/virtualFunctions,
          tests/solidity/ethereum/optimizer,
          tests/solidity/ethereum/fallback,
          tests/solidity/ethereum/conversions,
          tests/solidity/ethereum/array,
          tests/solidity/ethereum/calldata,
          tests/solidity/ethereum/multiSource,
          tests/solidity/ethereum/abiencodedecode,
          tests/solidity/ethereum/accessor,
          tests/solidity/ethereum/constants,
          tests/solidity/ethereum/tryCatch,
          tests/solidity/ethereum/builtinFunctions,
          tests/solidity/ethereum/enums,
          tests/solidity/ethereum/deployedCodeExclusion,
          tests/solidity/ethereum/constantEvaluator,
          tests/solidity/ethereum/using,
          tests/solidity/ethereum/userDefinedValueType,
          tests/solidity/ethereum/abiEncoderV2,
          tests/solidity/ethereum/libraries,
          tests/solidity/ethereum/exponentiation,
          tests/solidity/ethereum/underscore,
          tests/solidity/ethereum/state,
          tests/solidity/ethereum/freeFunctions,
          tests/solidity/ethereum/storage,
          tests/solidity/ethereum/interfaceID,
          tests/solidity/ethereum/receive,
          tests/solidity/ethereum/various,
          tests/solidity/ethereum/isoltestTesting,
          tests/solidity/ethereum/specialFunctions,
          tests/solidity/ethereum/statements,
          tests/solidity/ethereum/functionCall,
          tests/solidity/ethereum/cleanup,
          tests/solidity/ethereum/asmForLoop,
          tests/solidity/ethereum/inheritance,
          tests/solidity/ethereum/reverts,
          tests/solidity/ethereum/structs,
          tests/solidity/ethereum/memoryManagement,
          tests/solidity/ethereum/variables,
          tests/solidity/ethereum/functionSelector,
          tests/solidity/ethereum/arithmetics,
          tests/solidity/ethereum/getters,
          tests/solidity/ethereum/expressions,
          tests/solidity/ethereum/revertStrings,
          tests/solidity/ethereum/integer,
          tests/solidity/ethereum/functionTypes,
          tests/solidity/ethereum/salted_create,
          tests/solidity/ethereum/errors,
          tests/solidity/ethereum/literals,
          tests/solidity/ethereum/*.sol,
          tests/solidity/ethereum/abiEncoderV1,
          tests/solidity/ethereum/constructor,
          tests/solidity/ethereum/events,
          tests/solidity/ethereum/externalSource,
          tests/solidity/ethereum/payable,
          tests/solidity/ethereum/viaYul,
          tests/yul/instructions/*.yul,
          tests/yul/instructions/calldatacopy,
          tests/yul/instructions/event,
          tests/yul/near_call_abi/*.yul,
          tests/yul/near_call_abi/verbatim,
          tests/yul/near_call_abi/panic,
          tests/yul/precompiles,
          tests/yul/examples,
          tests/yul/simulations,
          tests/yul/semantic,
        ]
    name: Build VM with Compiler Tester + Run Compiler Tester
    runs-on: ubuntu-latest
    steps:
      - name: Checkout vm sources
        uses: actions/checkout@v4
        with:
          path: ${{ github.workspace }}/era_vm

      - name: LLVM Dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: llvm clang clang-tools build-essential lld ninja-build
          version: 1.0

      - uses: dtolnay/rust-toolchain@1.78.0
        with:
          toolchain: ${{ env.RUST_VERSION }}
          components: clippy

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            "."
            "era-compiler-tester"

      - name: Fetch zksync-llvm
        uses: dawidd6/action-download-artifact@v6
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: build-binaries.yml
          repo: matter-labs/era-compiler-llvm
          if_not_artifact_found: fail
          path: ${{ github.workspace }}/zksync-llvm
          workflow_conclusion: success
          name: llvm-bins-Linux-X64
          search_artifacts: true

      - name: Download zksolc compiler
        run: curl -L https://github.com/matter-labs/zksolc-bin/releases/download/v1.5.1/zksolc-linux-amd64-musl-v1.5.1 --output zksolc && chmod +x zksolc && sudo mv zksolc /usr/bin/zksolc

      - name: Download solc compiler
        run: curl -L https://github.com/ethereum/solidity/releases/download/v0.8.25/solc-static-linux --output solc && chmod +x solc && sudo mv solc /usr/bin/solc

      - name: Build compiler tester with Lambdaclass VM
        working-directory: ${{ github.workspace }}/zksync-llvm
        run: |
          rm -rfv llvm
          tar -xvf Linux-X64-target-final.tar.gz

      - name: Setup compiler-tester submodule
        working-directory: ${{ github.workspace }}/era_vm
        run: make submodules

      - name: Run compiler-tester tests
        working-directory: ${{ github.workspace }}/era_vm
        #run: make ci-test LLVM_PATH=$(pwd)/../zksync-llvm/target-llvm/target-final
        run: |
          export LLVM_SYS_170_PREFIX=$(pwd)/../zksync-llvm/target-llvm/target-final
          cd era-compiler-tester
          cargo run --features lambda_vm --release --bin compiler-tester -- --path ${{ matrix.testgroup }} --target EraVM
