name: "Cron Testing"

on:
  pull_request: # remove before merging
  schedule:
    # At the end of every day
    - cron: "0 0 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  RUST_VERSION: 1.78.0
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  test-with-compiler-tester:
    name: Run tests periodically
    runs-on: ubuntu-latest
    env:
      LLVM_PATH: /usr/lib/llvm-17/
      LLVM_SYS_170_PREFIX: /usr/lib/llvm-17/
    steps:
      - name: Checkout vm sources
        uses: actions/checkout@v4
        with:
          path: ${{ github.workspace }}/era_vm

      - name: Download zksolc compiler
        run: curl -L https://github.com/matter-labs/zksolc-bin/releases/download/v1.5.1/zksolc-linux-amd64-musl-v1.5.1 --output zksolc && chmod +x zksolc && sudo mv zksolc /usr/bin/zksolc

      - name: Download solc compiler
        run: curl -L https://github.com/ethereum/solidity/releases/download/v0.8.25/solc-static-linux --output solc && chmod +x solc && sudo mv solc /usr/bin/solc

      - name: Add LLVM deb repository
        uses: myci-actions/add-deb-repo@10
        with:
          repo: deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-17 main
          repo-name: llvm-repo
          keys-asc: https://apt.llvm.org/llvm-snapshot.gpg.key

      - name: Install LLVM
        run: sudo apt-get install llvm-17 llvm-17-dev llvm-17-runtime clang-17 clang-tools-17 lld-17 libpolly-17-dev libmlir-17-dev mlir-17-tools

      - name: Setup compiler-tester submodule
        working-directory: ${{ github.workspace }}/era_vm
        run: make submodules

      - name: Run compiler-tester tests
        working-directory: ${{ github.workspace }}/era_vm
        run: cd era-compiler-tester && cargo run --verbose --features lambda_vm --release --bin compiler-tester -- --path  tests/solidity/simple/yul_instructions/ --target EraVM --disable-deployer
