name: "Cron Testing"

on:
  pull_request: # remove before merging
  schedule:
    # At the end of every day
    - cron: "0 0 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  RUST_VERSION: 1.78.0
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Rustup toolchain install
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_VERSION }}

      - name: Run cargo check
        run: cargo check --workspace --all-features --all-targets

  test-with-compiler-tester:
    name: Build VM with Compiler Tester + Run Compiler Tester
    runs-on: ubuntu-latest
    env:
      LLVM_PATH: ${{ github.workspace }}/zksync-llvm/target-llvm/target-final
    steps:
      - name: Checkout vm sources
        uses: actions/checkout@v4
        with:
          path: ${{ github.workspace }}/era_vm

      - name: LLVM Dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: llvm clang clang-tools build-essential lld ninja-build
          version: 1.0

      - uses: dtolnay/rust-toolchain@1.78.0
        with:
          toolchain: ${{ env.RUST_VERSION }}
          components: clippy

      - uses: Swatinem/rust-cache@v2

      - name: Fetch zksync-llvm
        uses: dawidd6/action-download-artifact@v6
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: build-binaries.yml
          repo: matter-labs/era-compiler-llvm
          if_not_artifact_found: fail
          path: ${{ github.workspace }}/zksync-llvm
          workflow_conclusion: success
          name: llvm-bins-Linux-X64
          search_artifacts: true

      - name: Download zksolc compiler
        run: curl -L https://github.com/matter-labs/zksolc-bin/releases/download/v1.5.1/zksolc-linux-amd64-musl-v1.5.1 --output zksolc && chmod +x zksolc && sudo mv zksolc /usr/bin/zksolc

      - name: Download solc compiler
        run: curl -L https://github.com/ethereum/solidity/releases/download/v0.8.25/solc-static-linux --output solc && chmod +x solc && sudo mv solc /usr/bin/solc

      - name: Build compiler tester with Lambdaclass VM
        working-directory: ${{ github.workspace }}/zksync-llvm
        run: |
          rm -rfv llvm
          tar -xvf Linux-X64-target-final.tar.gz

      - name: Setup compiler-tester submodule
        working-directory: ${{ github.workspace }}/era_vm
        run: make submodules

      - name: Run compiler-tester tests
        working-directory: ${{ github.workspace }}/era_vm
        run: export LLVM_SYS_170_PREFIX=$(LLVM_PATH) && cd era-compiler-tester && cargo run --verbose --features lambda_vm --release --bin compiler-tester -- --path  tests/solidity/simple/yul_instructions/ --target EraVM
